name: Flawfinder Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flawfinder-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Flawfinder
      run: pip install flawfinder
    - name: Run Flawfinder
      run: flawfinder --csv ./ > test.csv
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: my-artifact # NOTE: same artifact name
          path: test.csv
      
